config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :user do
    resources :members
    resources :events
    resources :postulations
    root to: "events#index"
  end
  scope module: "frontend" do
    resources :postulations
    resources :members
    resources :events
    get "contact", to: "frontends#contact"
    get "talca", to: "frontends#talca"
    get "work-with-us", to: "frontends#work_with_us"
    post "send_email", to: "frontends#send_email"
    root to: "frontends#index"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

end

app/models/user/event.rb
class User::Event < ApplicationRecord
  has_many_attached :images
  has_one_attached :file
  has_one_attached :main_image
  has_one_attached :video

  has_many :postulations, class_name: "Postulation", foreign_key: :user_event_id, dependent: :destroy

  scope :next_events, -> { where("date > ?", Date.today) }
  scope :past_events, -> { where("date < ?", Date.today) }
  scope :talca_events, -> { where(is_talca: true) }
  scope :active_events, -> { where(active: true) }

  before_save :unique_slug

  def unique_slug
    self.slug = if self.slug.blank?
                  set_slug(self.title.parameterize)
                else
                  set_slug(self.slug.parameterize)
                end
  end

  def set_slug(val)
    event_by_slug = User::Event.find_by(slug: val)
    if event_by_slug.present? && event_by_slug != self
      random_number = rand(1000..9999)
      slug_split = val.split("-")
      if slug_split[-1].match? /^[0-9]+$/
        if slug_split.count > 1
          temp = slug_split[0..-2].join("-")
        else
          temp = slug_split[0]
        end
        set_slug(temp + "-" + random_number.to_s)
      else
        set_slug(val + "-" + random_number.to_s)
      end
    else
      val
    end
  end
end

app/models/user/member.rb
class User::Member < ApplicationRecord
    has_one_attached :image
end

app/controllers/frontend/events_controller.rb
class Frontend::EventsController < Frontend::FrontendsController
  before_action :set_user_event, only: [:show]

  # GET /user/events
  # GET /user/events.json
  def index
    @past_events = User::Event.active_events.past_events
    @next_events = User::Event.active_events.next_events
  end

  # GET /user/events/1
  # GET /user/events/1.json
  def show
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_event
    @user_event = User::Event.find_by(slug: params[:id])
  end
end

app/controllers/user/events_controller.rb
class User::EventsController < User::UsersController
  before_action :set_user_event, only: [:show, :edit, :update, :destroy]

  # GET /user/events
  # GET /user/events.json
  def index
    @user_events = User::Event.all.paginate(page: params[:page], per_page: 10)
  end

  # GET /user/events/1
  # GET /user/events/1.json
  def show
  end

  # GET /user/events/new
  def new
    @user_event = User::Event.new
  end

  # GET /user/events/1/edit
  def edit
  end

  # POST /user/events
  # POST /user/events.json
  def create
    @user_event = User::Event.new(user_event_params)

    respond_to do |format|
      if @user_event.save
        format.html { redirect_to @user_event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @user_event }
      else
        format.html { render :new }
        format.json { render json: @user_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user/events/1
  # PATCH/PUT /user/events/1.json
  def update
    respond_to do |format|
      if @user_event.update(user_event_params)
        format.html { redirect_to @user_event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @user_event }
      else
        format.html { render :edit }
        format.json { render json: @user_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user/events/1
  # DELETE /user/events/1.json
  def destroy
    @user_event.destroy
    respond_to do |format|
      format.html { redirect_to user_events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_event
    @user_event = User::Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_event_params
    params.require(:user_event).permit(:title, :description, :date, :is_talca, :file, :main_image, :active, :video, images: [])
  end
end

app/controllers/user/members_controller.rb
class User::MembersController < User::UsersController
  before_action :set_user_member, only: [:show, :edit, :update, :destroy]

  # GET /user/members
  # GET /user/members.json
  def index
    @user_members = User::Member.all
  end

  # GET /user/members/1
  # GET /user/members/1.json
  def show
  end

  # GET /user/members/new
  def new
    @user_member = User::Member.new
  end

  # GET /user/members/1/edit
  def edit
  end

  # POST /user/members
  # POST /user/members.json
  def create
    @user_member = User::Member.new(user_member_params)

    respond_to do |format|
      if @user_member.save
        format.html { redirect_to @user_member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @user_member }
      else
        format.html { render :new }
        format.json { render json: @user_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user/members/1
  # PATCH/PUT /user/members/1.json
  def update
    respond_to do |format|
      if @user_member.update(user_member_params)
        format.html { redirect_to @user_member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_member }
      else
        format.html { render :edit }
        format.json { render json: @user_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user/members/1
  # DELETE /user/members/1.json
  def destroy
    @user_member.destroy
    respond_to do |format|
      format.html { redirect_to user_members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_member
      @user_member = User::Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_member_params
      params.require(:user_member).permit(:name, :lastname, :email, :summary, :phone, :image)
    end
end

app/controllers/user/postulations_controller.rb
class User::PostulationsController < User::UsersController
  before_action :set_postulation, only: [:show, :edit, :update, :destroy]

  # GET /postulations
  # GET /postulations.json
  def index
    @postulations = Postulation.all.paginate(page: params[:page], per_page: 10)
  end

  # GET /postulations/1
  # GET /postulations/1.json
  def show
  end

  # GET /postulations/new
  def new
    @postulation = Postulation.new
  end

  # GET /postulations/1/edit
  def edit
  end

  # POST /postulations
  # POST /postulations.json
  def create
    @postulation = Postulation.new(postulation_params)

    respond_to do |format|
      if @postulation.save
        format.html { redirect_to @postulation, notice: "Postulation was successfully created." }
        format.json { render :show, status: :created, location: @postulation }
      else
        format.html { render :new }
        format.json { render json: @postulation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postulations/1
  # PATCH/PUT /postulations/1.json
  def update
    respond_to do |format|
      if @postulation.update(postulation_params)
        format.html { redirect_to @postulation, notice: "Postulation was successfully updated." }
        format.json { render :show, status: :ok, location: @postulation }
      else
        format.html { render :edit }
        format.json { render json: @postulation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postulations/1
  # DELETE /postulations/1.json
  def destroy
    @postulation.destroy
    respond_to do |format|
      format.html { redirect_to user_postulations_path, notice: "Postulation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_postulation
    @postulation = Postulation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def postulation_params
    params.require(:postulation).permit(:name, :lastname, :email, :message, :user_event_id)
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!
  layout 'user'
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/user/events_helper.rb
module User::EventsHelper
end

app/helpers/user/members_helper.rb
module User::MembersHelper
end

app/views/user/events/_form.html.erb
<%= form_with(model: user_event, local: true) do |form| %>
  <% if user_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_event.errors.count, "error") %> prohibited this user_event from being saved:</h2>
      <ul>
      <% user_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="card">
    <div class="card-header">
      <h4>Formulario</h4>
    </div>
    <div class="card-body">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, required: true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :date %>
        <%= form.datetime_select :date, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :is_talca %>
        <%= form.check_box :is_talca, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :images %>
        <%= form.file_field :images, multiple: true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :main_image %>
        <%= form.file_field :main_image, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :file %>
        <%= form.file_field :file, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :video %>
        <%= form.file_field :video, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :active %>
        <%= form.check_box :active, class: 'form-control', checked: true %>
      </div>
      <div class="card-footer text-right">
        <%= form.submit class:"btn btn-primary mr-1" %>
      </div>
    </div>
  </div>
<% end %>

app/views/user/events/index.html.erb
<div class="section-header">
  <h1>Eventos</h1>
</div>
<div class="section-body center">
  <div class="card">
    <div class="card-header">
      <h4>Lista de eventos</h4>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered table-md">
          <tr>
            <th>#</th>
            <th>Titulo</th>
            <th>Fecha del Evento</th>
            <th>Fecha Creación</th>
            <th>Acciones</th>
          </tr>
          <% @user_events.each do |user_event| %>
            <tr>
              <td><%= user_event.id %></td>
              <td><%= user_event.title %></td>
              <td><%= user_event.date.strftime("%d/%m/%Y") %></td>
              <td><%= user_event.created_at.strftime("%d/%m/%Y") %></td>
              <td><%= link_to 'Ver', user_event, class: 'btn btn-success' %>
              <%= link_to 'Editar', edit_user_event_path(user_event), class: 'btn btn-primary' %>
              <%= link_to 'Eliminar', user_event, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </table>
          <%= will_paginate @user_events %>
        <%= link_to 'Nuevo evento', new_user_event_path %>
      </div>
    </div>
  </div>
</div>

app/views/user/events/show.html.erb
<p id="notice"><%= notice %></p>
<div class="section-header">
  <h1><%= @user_event.title %></h1>
</div>
<div class="card">
  <div class="card-body">
    <% if @user_event.main_image.attachment %>
      <%= image_tag @user_event.main_image.variant(resize: '500x'), style: 'height: 200px; width: 300px; object-fit: cover;' %>
    <% end %>
    <p>
      <strong>Title:</strong>
      <%= @user_event.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @user_event.description %>
    </p>

    <p>
      <strong>Date:</strong>
      <%= @user_event.date %>
    </p>
    <p>
      <strong>
        Video
      </strong>
    </p>
    <% if @user_event.video.attached? %>
      <%= video_tag @user_event.video.service_url, size: "720x480", controls: true %>
    <% end %>
    <p>
      <strong>Galería</strong>
    </p>
      <% @user_event.images.each do |image| %>
        <%= image_tag image.variant(resize: '500x'), style: 'height: 200px; width: 300px; object-fit: cover;' %>
      <% end %>
  </div>
</div>

<%= link_to 'Edit', edit_user_event_path(@user_event) %> |
<%= link_to 'Back', user_events_path %>