config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :user do
    resources :members
    resources :events
    resources :postulations
    root to: "events#index"
  end
  scope module: "frontend" do
    resources :postulations
    resources :members
    resources :events
    get "contact", to: "frontends#contact"
    get "talca", to: "frontends#talca"
    get "work-with-us", to: "frontends#work_with_us"
    post "send_email", to: "frontends#send_email"
    root to: "frontends#index"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user/event.rb
class User::Event < ApplicationRecord
  has_many_attached :images
  has_one_attached :file
  has_one_attached :main_image
  has_one_attached :video

  has_many :postulations, class_name: "Postulation", foreign_key: :user_event_id, dependent: :destroy

  scope :next_events, -> { where("date > ?", Date.today) }
  scope :past_events, -> { where("date < ?", Date.today) }
  scope :talca_events, -> { where(is_talca: true) }
  scope :active_events, -> { where(active: true) }

  before_save :unique_slug

  def unique_slug
    self.slug = if self.slug.blank?
                  set_slug(self.title.parameterize)
                else
                  set_slug(self.slug.parameterize)
                end
  end

  def set_slug(val)
    event_by_slug = User::Event.find_by(slug: val)
    if event_by_slug.present? && event_by_slug != self
      random_number = rand(1000..9999)
      slug_split = val.split("-")
      if slug_split[-1].match? /^[0-9]+$/
        if slug_split.count > 1
          temp = slug_split[0..-2].join("-")
        else
          temp = slug_split[0]
        end
        set_slug(temp + "-" + random_number.to_s)
      else
        set_slug(val + "-" + random_number.to_s)
      end
    else
      val
    end
  end
end

app/controllers/frontend/events_controller.rb
class Frontend::EventsController < Frontend::FrontendsController
  before_action :set_user_event, only: [:show]

  # GET /user/events
  # GET /user/events.json
  def index
    @past_events = User::Event.active_events.past_events
    @next_events = User::Event.active_events.next_events
  end

  # GET /user/events/1
  # GET /user/events/1.json
  def show
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_event
    @user_event = User::Event.find_by(slug: params[:id])
  end
end

app/controllers/frontend/frontends_controller.rb
class Frontend::FrontendsController < ApplicationController
  layout "application"

  def index
    @events = User::Event.active_events.order(created_at: :desc)
  end

  def contact
  end

  def send_email
    name = params[:name]
    email = params[:email]
    message = params[:message]
    phone = params[:phone]
    UserNotifierMailer.send_contact(name, email, message, phone).deliver
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Correo enviado exitosamente." }
    end
  end

  def talca
    @talca_events = User::Event.talca_events
  end

  def work_with_us
  end
end

app/controllers/frontend/members_controller.rb
class Frontend::MembersController < Frontend::FrontendsController
  before_action :set_user_member, only: [:show]

  # GET /user/members
  # GET /user/members.json
  def index
    @members = User::Member.all
  end

  # GET /user/members/1
  # GET /user/members/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_member
      @user_member = User::Member.find(params[:id])
    end
end

app/controllers/frontend/postulations_controller.rb
class Frontend::PostulationsController < Frontend::FrontendsController
  # GET /postulations/new
  def new
    @postulation = Postulation.new
    @events = User::Event.active_events.next_events
  end

  # POST /postulations
  # POST /postulations.json
  def create
    @postulation = Postulation.new(postulation_params)

    respond_to do |format|
      if @postulation.save
        format.html { redirect_to root_path, notice: "Su postulación fué enviada con éxito." }
        format.json { render :show, status: :created, location: @postulation }
      else
        format.html { render :new }
        format.json { render json: @postulation.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def postulation_params
    params.require(:postulation).permit(:name, :lastname, :email, :message, :user_event_id, :phone, :stand, images: [])
  end
end

app/controllers/user/events_controller.rb
class User::EventsController < User::UsersController
  before_action :set_user_event, only: [:show, :edit, :update, :destroy]

  # GET /user/events
  # GET /user/events.json
  def index
    @user_events = User::Event.all.paginate(page: params[:page], per_page: 10)
  end

  # GET /user/events/1
  # GET /user/events/1.json
  def show
  end

  # GET /user/events/new
  def new
    @user_event = User::Event.new
  end

  # GET /user/events/1/edit
  def edit
  end

  # POST /user/events
  # POST /user/events.json
  def create
    @user_event = User::Event.new(user_event_params)

    respond_to do |format|
      if @user_event.save
        format.html { redirect_to @user_event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @user_event }
      else
        format.html { render :new }
        format.json { render json: @user_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user/events/1
  # PATCH/PUT /user/events/1.json
  def update
    respond_to do |format|
      if @user_event.update(user_event_params)
        format.html { redirect_to @user_event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @user_event }
      else
        format.html { render :edit }
        format.json { render json: @user_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user/events/1
  # DELETE /user/events/1.json
  def destroy
    @user_event.destroy
    respond_to do |format|
      format.html { redirect_to user_events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_event
    @user_event = User::Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_event_params
    params.require(:user_event).permit(:title, :description, :date, :is_talca, :file, :main_image, :active, :video, images: [])
  end
end

app/helpers/user/events_helper.rb
module User::EventsHelper
end

app/views/frontend/events/_form.html.erb
<%= form_with(model: user_event, local: true) do |form| %>
  <% if user_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_event.errors.count, "error") %> prohibited this user_event from being saved:</h2>

      <ul>
      <% user_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="card">
    <div class="card-header">
      <h4>Formulario</h4>
    </div>
    <div class="card-body">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :date %>
        <%= form.datetime_select :date, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :images %>
        <%= form.file_field :images, multiple: true, class: 'form-control' %>
      </div>
      <div class="card-footer text-right">
        <%= form.submit class:"btn btn-primary mr-1" %>
      </div>
    </div>
  </div>
<% end %>

app/views/frontend/events/edit.html.erb
<div class="section-header">
  <h1>Editar Evento</h1>
</div>

<%= render 'form', user_event: @user_event %>

<%= link_to 'Show', @user_event %> |
<%= link_to 'Back', user_events_path %>

app/views/frontend/events/index.html.erb
<div class="col-lg-12 text-center">
	<h1 class="text-uppercase font-weight-bold-max" style="font-size: 50px; margin-bottom: -5px">Próximos eventos</h1>
	<div class="row pt-5">
		<% @next_events.each do |event| %>
			<div class="col-md-4 pt-2">
				<div class="card" style="min-width: 21rem;">
					<% if event.main_image.attachment %>
						<%= image_tag event.main_image.variant(resize: "x260"), style:'height: 160px; object-fit: cover;'%>
					<% else %>
						<%= image_tag asset_url("computador.png"), style:'height: 160px; object-fit: cover;'%>
					<% end %>
					<div class="card-body">
						<h5 class="card-title"><%= event.title %></h5>
						<p class="card-text"><%= event.description[0..25] + '...' %></p>
						<%= link_to "Ver", event_path(event.slug), class: 'btn btn-primary btn-block' %>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>
<hr class="divider my-4">
<div class="col-lg-12 text-center">
	<h1 class="text-uppercase font-weight-bold-max" style="font-size: 50px; margin-bottom: -5px">Eventos realizados</h1>
	<div class="row pt-5">
		<% @past_events.each do |event| %>
			<div class="col-md-4 pt-2 text-center d-flex justify-content-center">
				<div class="card" style="min-width: 21rem;">
					<% if event.main_image.attachment %>
						<%= image_tag event.main_image.variant(resize: "x260"), style:'height: 160px; object-fit: cover;'%>
					<% else %>
						<%= image_tag asset_url("computador.png"), style:'height: 160px; object-fit: cover;'%>
					<% end %>
					<div class="card-body">
						<h5 class="card-title"><%= event.title %></h5>
						<p class="card-text"><%= event.description[0..25] + '...' %></p>
						<%= link_to "Ver", event_path(event.slug), class: 'btn btn-primary btn-block' %>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/frontend/events/new.html.erb
<div class="section-header">
  <h1>Nuevo Evento</h1>
</div>
<%= render 'form', user_event: @user_event %>

<%= link_to 'Volver', user_events_path %>

app/views/frontend/events/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card">
  <div class="card-body">
    <div class="section-header">
      <div class="text-uppercase font-weight-bold-max h1 text-center"><%= @user_event.title %></div>
    </div>
    <div class="col-md-12 text-center">
      <% if @user_event.video.attached? %>
        <%= video_tag @user_event.video.service_url, size: "720x480", controls: true %>
      <% elsif @user_event.main_image.attachment %>
          <%= image_tag @user_event.main_image.variant(resize: "x500"), style:'height: 400px; width: 400px; object-fit: cover;'%>
        <% else %>
          <%= image_tag asset_url("computador.png"), style:'height: 160px; object-fit: cover;'%>
        <% end %>
    </div>
    <div class="col-md-12 pt-4">
      <%= @user_event.description %>
    </div>
    <div class="col-md-12 text-center">
      <%= link_to "Descarga las bases aquí", @user_event.file, class: "h4" if @user_event.file.attached? %>
    </div>
    <% if @user_event.images.attached? %>
      <div class="text-center">
        <div class="h2 font-weight-bold pt-4">
          Galería
        </div>
        <div class='row'>
          <% @user_event.images.each do |image| %>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">  
              <a class="thumbnail" data-toggle="modal" data-title=""
                data-image="<%= url_for(image)%>"
                data-target="#image-gallery">
              <%= image_tag image, class: 'img-thumbnail', style: "height: 250px; width: 250px; object-fit: cover;" %>
              </a>
            </div>
          <% end %>
        </div>
      </div>
      <% end %>
    <div class="text-right">
      <%= @user_event.date.strftime("%d-%m-%y") %>
    </div>
  </div>
</div>
<% if @user_event.date > Date.today %>
  <%= link_to 'Postular a este evento', new_postulation_path, class: 'btn btn-primary btn-block mb-2 mt-2' %>
<% end %>
<div class="modal fade" id="image-gallery" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="image-gallery-title"></h4>
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span>
            </button>
        </div>
        <div class="modal-body">
            <img id="image-gallery-image" class="img-responsive col-md-12" src="">
        </div>
        <div class="modal-footer">
            <%# <button type="button" class="btn btn-secondary float-left" id="show-previous-image">Anterior
            </button>

            <button type="button" id="show-next-image" class="btn btn-secondary float-right">Siguiente
            </button> %>
        </div>
      </div>
    </div>
  </div>
<div class="text-md-center">
  <%= link_to 'Volver', events_path %>
</div>