config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :user do
    resources :members
    resources :events
    resources :postulations
    root to: "events#index"
  end
  scope module: "frontend" do
    resources :postulations
    resources :members
    resources :events
    get "contact", to: "frontends#contact"
    get "talca", to: "frontends#talca"
    get "work-with-us", to: "frontends#work_with_us"
    post "send_email", to: "frontends#send_email"
    root to: "frontends#index"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_google_analytics.html.erb
<% if Rails.env.production? %>
<script async src="https://www.googletagmanager.com/gtag/js?id=<%= Rails.application.credentials.dig(:google_analytics) %>"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', '<%= Rails.application.credentials.dig(:google_analytics) %>');
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>La Ciudad Cultural</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="La Ciudad Cultural, un espacio cultural en Chile.">
    <%= stylesheet_link_tag    'frontend', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/google_analytics' %>
    <%= javascript_include_tag 'frontend', 'data-turbolinks-track': 'reload' %>
  </head>

 <body id="page-top col-lg-12">

  <!-- Navigation -->
  <div class="container">
    <header class="header">
      <a class="navbar-brand js-scroll-trigger" href="/"></a><%= link_to (image_tag asset_url("logo.png"), class: 'img', style: ' padding-left: 20px; max-height: 80px'), root_path %>
      <input class="menu-btn" type="checkbox" id="menu-btn" />
      <label class="menu-icon" for="menu-btn"><span class="navicon"></span></label>
      <ul class="menu">
        <li class="nav-item">
          <%= link_to "Somos", members_path, class:'nav-link js-scroll-trigger'%>
        </li>
        <li class="nav-item">
          <%= link_to "Eventos", events_path, class:'nav-link js-scroll-trigger'%>
        </li>
        <li class="nav-item">
          <%= link_to "Contacto", contact_path, class:'nav-link js-scroll-trigger'%>
        </li>
      </ul>
    </header>
  </div>
  <div class="container pb-4">
    <p class="notice alert-success"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
<%= link_to (image_tag asset_url("whatsapp.png"), class: 'img', style: "height: 80px; position: fixed; z-index: 9; bottom: 0; right: 0;"), "https://wa.me/56947423460?text=Mensaje desde el sitio web: "%>

  <footer id="sticky-footer" class="py-4 bg-light text-dark-50">
    <div class="container text-center">
      <small>Copyright &copy; La Ciudad Cultural | </small>
      <small>Developed by <a href="https://www.linkedin.com/in/jeremias-gutierrez-araya-490235101" target="_blank">Jeremías Gutiérrez</a></small>
    </div>
  </footer>
</body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CiudadCultural</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <%= stylesheet_link_tag    'user', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'user', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div id="app">
      <div class="main-wrapper">
        <div class="navbar-bg"></div>
        <nav class="navbar navbar-expand-lg main-navbar">
          <form class="form-inline mr-auto">
            <ul class="navbar-nav mr-3">
              <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
              <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
            </ul>
            
          </form>
          <ul class="navbar-nav navbar-right">
            <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
              <img alt="image" src="/images/avatar/avatar-1.png" class="rounded-circle mr-1">
              <div class="d-sm-none d-lg-inline-block">Hola, <%= current_user.name %></div></a>
              <div class="dropdown-menu dropdown-menu-right">
                <div class="dropdown"></div>
                <%= link_to 'Salir', destroy_user_session_path, method: :delete, class: 'dropdown-item has-icon text-danger'%>
              </div>
            </li>
          </ul>
        </nav>
        <div class="main-sidebar">
          <aside id="sidebar-wrapper">
            <div class="sidebar-brand">
              <a href="#">Ciudad Cultural</a>
            </div>
            <div class="sidebar-brand sidebar-brand-sm">
              <a href="index.html">CC</a>
            </div>
            <ul class="sidebar-menu">              
                <li class="menu-header">Inicio</li>
                <li>
                  <%=link_to user_events_path, class: 'nav-link' do %>
                    <i class="far fa-calendar-alt"></i><span>Eventos</span>
                  <% end %>
                </li>
                <li>
                  <%=link_to user_members_path, class: 'nav-link' do %>
                    <i class="far fa-user"></i><span>Miembros</span>
                  <% end %>
                </li>
                <li>
                  <%=link_to user_postulations_path, class: 'nav-link' do %>
                    <i class="far fa-user"></i><span>Postulaciones</span>
                  <% end %>
                </li>
              </ul>

              <div class="mt-4 mb-4 p-3 hide-sidebar-mini">
                <%=link_to root_path, class: 'btn btn-primary btn-lg btn-block btn-icon-split' do %>
                  <i class="fas fa-rocket"></i><span>Ver modo visitas</span>
                <% end %>
              </div>
          </aside>
        </div>

        <!-- Main Content -->
        <div class="main-content">
          <section class="section">
            <p class="notice alert-success"><%= notice %></p>
            <p class="alert"><%= alert %></p>
            <%= yield %>
          </section>
        </div>
        <footer class="main-footer">
          <div class="footer-left">
            Copyright &copy; 2019 <div class="bullet"></div> Creado por Jeremías Gutiérrez
          </div>
          <div class="footer-right">
            v1.0
          </div>
        </footer>
      </div>
    </div>

    <!-- General JS Scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
</body>
</html>